name: VoidAirRace
description: Void air race Minigame
version: '0.1'
author: qR
main: io.github.qingranqae.voidairrace.VoidAirRacePlugin
api-version: '1.21.11'

commands:
  vardebug:
    description: 测试命令
    usage: /help <command>
    permission: void_air_race.debug
    permission-message: 无权执行
  match:
    description: 比赛管理命令
    usage: /help <command>
    permission: void_air_race.command.match
    permission-message: 无权执行
  game_map:
    description: 地图管理命令
    usage: /help <command>
    permission: void_air_race.command.game_map
    permission-message: 无权执行
  player_manager:
    description: 玩家管理命令
    usage: /help <command>
    permission: void_air_race.command.player_manager
    permission-message: 无权执行

permissions:
  void_air_race.debug:
    description: ''
    default: op
  void_air_race.command.match:
    description: 比赛管理命令权限
    default: op
  void_air_race.command.game_map:
    description: 地图管理命令权限
    default: op
  void_air_race.command.player_manager:
    description: 玩家管理命令权限
    default: op